INSERT INTO SPACESHIPS (ID, NAME, FILM, CREATION_DATE) VALUES(1, 'Millennium Falcon', 'Star Wars', CURRENT_DATE);
INSERT INTO SPACESHIPS (ID, NAME, FILM, CREATION_DATE) VALUES(2, 'USS Enterprise', 'Star Trek', CURRENT_DATE);
INSERT INTO SPACESHIPS (ID, NAME, FILM, CREATION_DATE) VALUES(3, 'Imperial Star Destroyer', 'Star Wars', CURRENT_DATE);